### ISSUE TITLE
it's not working on colab anymore

### ISSUE THREAD

**Issue by myselfsumandutta** [fenneishi/Fooocus-Control#27]
Changed the directory name (Fooocus-ControlNet-SDXL) but still getting this error - 

Traceback (most recent call last):
  File "/content/Fooocus-ControlNet-SDXL/entry_with_update.py", line 47, in <module>
    from launch import *
  File "/content/Fooocus-ControlNet-SDXL/launch.py", line 10, in <module>
    from modules.path import modelfile_path, lorafile_path, vae_approx_path, fooocus_expansion_path, \
  File "/content/Fooocus-ControlNet-SDXL/modules/path.py", line 10, in <module>
    from fooocus_extras.controlnet_preprocess_model.PyramidCanny import PyramidCanny
  File "/content/Fooocus-ControlNet-SDXL/fooocus_extras/controlnet_preprocess_model/PyramidCanny/__init__.py", line 4, in <module>
    from fooocus_extras.controlnet_preprocess_model.ZeoDepth import ZoeDetector
  File "/content/Fooocus-ControlNet-SDXL/fooocus_extras/controlnet_preprocess_model/ZeoDepth/__init__.py", line 9, in <module>
    from einops import rearrange
ModuleNotFoundError: No module named 'einops'

**Comment by sitzbrau** [comment]
i've resolved this error executing this before

`!pip3 install --force einops==0.4.1`

**Comment by briziomusic** [comment]
> i've resolved this error executing this before
> 
> `!pip3 install --force einops==0.4.1`

Hello, could you please share a working colab file or rows?
I'm not able to run it in google colab.
Thanks
